name: "♻️ Terraform Github Repos"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/github/repositories/**"
    branches:
      - main
  push:
    paths:
      - "terraform/github/repositories/**"
    branches: ["main"]

jobs:
  terraform-github-repos:
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      path: "terraform/github/repositories"
      terraform_version: "1.6.6"
    secrets:
      iam_role: ${{ secrets.TERRAFORM_GITHUB_REPOS_S3_ROLE_ARN_PROD }}
      github_token: ${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
