name: "♻️ Terraform Github Repos"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/github/**"
    branches:
      - main
  push:
    paths:
      - "terraform/github/**"
    branches: [ "main" ]

env:
  TERRAFORM_VERSION: "1.6.6"
  TF_VAR_github_token: ${{ secrets.TERRAFORM_ADMIN_DEV_LEVG }}

jobs:
  terraform:
    name: "Terraform Github Repos"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    strategy:
      matrix:
        path:
          - "repositories"
    defaults:
      run:
        working-directory: "terraform/github/${{ matrix.path }}"
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.TERRAFORM_GITHUB_REPOS_S3_ROLE_ARN_PROD}}
        aws-region: eu-west-2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -diff -no-color
      continue-on-error: false

    - name: Terraform Init
      id: init
      run: ls -latr; terraform init -input=false -no-color

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Remove from State
      id: state-remove
      run: |
        terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["KUBE_CERT"]' 
        terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["KUBE_CLUSTER"]' 
        terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["KUBE_NAMESPACE"]' 
        terraform state rm 'module.operations-engineering-reports.github_actions_secret.default["KUBE_TOKEN"]' 
      continue-on-error: false

    - name: Terraform Import
      id: import
      run: |
        terraform import -input=false -no-color 'module.operations-engineering-reports.github_actions_secret.default["KUBE_CERT"]' operations-engineering-reports/KUBE_CERT
        terraform import -input=false -no-color 'module.operations-engineering-reports.github_actions_secret.default["KUBE_CLUSTER"]' operations-engineering-reports/KUBE_CLUSTER
        terraform import -input=false -no-color 'module.operations-engineering-reports.github_actions_secret.default["KUBE_NAMESPACE"]' operations-engineering-reports/KUBE_NAMESPACE
        terraform import -input=false -no-color 'module.operations-engineering-reports.github_actions_secret.default["KUBE_TOKEN"]' operations-engineering-reports/KUBE_TOKEN
      continue-on-error: false

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -no-color
      continue-on-error: false

    - name: Post Plan to GitHub PR
      uses: mshick/add-pr-comment@v1
      with:
        allow-repeats: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ## ${{ matrix.path }} plan
          ```
          ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
          ```

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      id: apply
      run: terraform apply -input=false -no-color -auto-approve
