name: "♻️ Terraform GitHub Teams"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/github/teams/**"
    branches:
      - main
  push:
    paths:
      - "terraform/github/teams/**"
    branches: ["main"]

jobs:
  terraform-github-teams:
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      path: "terraform/github/teams"
      terraform_version: "1.6.6"
      stack_name: "github teams"
    secrets:
      iam_role: ${{ secrets.TERRAFORM_GITHUB_TEAMS_S3_ROLE_ARN_PROD }}
      repo_github_token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      env: |
        TF_VAR_github_token=${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
