name: "♻️ Terraform Github Repos"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/github/repositories/**"
    branches:
      - main
  push:
    paths:
      - "terraform/github/repositories/**"
    branches: ["main"]

jobs:
  configure-aws-profiles:
    name: "Configure AWS profiles"
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for accessing AWS Secrets Manager in the DSD account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_SECRETS_MANAGER_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Save AWS credentials for accessing AWS Secrets Manager in the DSD account to a new profile
        run: |
          aws configure set region ${{ env.AWS_REGION }} --profile dsd_secret_manager_access_profile
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile dsd_secret_manager_access_profile
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile dsd_secret_manager_access_profile
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile dsd_secret_manager_access_profile

      - uses: actions/upload-artifact@v4
        name: Export AWS configuration
        with:
          name: aws-config
          path: ~/.aws/config
          retention-days: 1

  terraform-github-repos:
    needs: configure-aws-profiles
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      path: "terraform/github/repositories"
      terraform_version: "1.6.6"
    secrets:
      iam_role: ${{ secrets.TERRAFORM_GITHUB_REPOS_S3_ROLE_ARN_PROD }}
      repo_github_token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      env: |
        TF_VAR_github_token=${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
