name: "♻️ Terraform Github Repos"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/github/repositories/**"
    branches:
      - main
  push:
    paths:
      - "terraform/github/repositories/**"
    branches: ["main"]

jobs:
  configure-aws-profiles:
    uses: ./.github/workflows/reusable-workflow-configure-aws-profiles.yml
    with:
      profile_name: "dsd_secret_manager_access_profile"
    secrets:
      iam_role: ${{ secrets.AWS_SECRETS_MANAGER_ROLE_ARN }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_public_key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

  terraform-github-repos:
    needs: configure-aws-profiles
    uses: ./.github/workflows/reusable-workflow-terraform.yml
    with:
      path: "terraform/github/repositories"
      terraform_version: "1.6.6"
      name: "github repositories"
      aws_profiles: true
    secrets:
      iam_role: ${{ secrets.TERRAFORM_GITHUB_REPOS_S3_ROLE_ARN_PROD }}
      repo_github_token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_public_key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      env: |
        TF_VAR_github_token=${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
