name: "Terraform for s3 to cloudtrail integration for github logs"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/log_streaming/**"
    branches:
      - main
  push:
    paths:
      - "terraform/log_streaming/**"
    branches: ["main"]

env:
  TERRAFORM_VERSION: "1.6.6"

jobs:
  cloudtrail-streaming-terraform:
    name: "CloudTrail Streaming Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: "terraform/log_streaming"
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials for Infra Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DSD_CICD_ADMIN_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Terraform Format Check
        id: fmt-check
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: ls -latr; terraform init -input=false -no-color

      - name: Build Lambdas
        id: build-lambdas
        run: cd .terraform/modules/github-cloudtrail-auditlog && make all

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        id: apply
        run: terraform apply -input=false -no-color -auto-approve
