name: "♻️ Configure AWS Profile"

on:
    workflow_call:
        inputs:
            region:
              required: true
              type: string
            profile:
              required: true
              type: string
        secrets:
            role-arn:
              required: true

jobs:
  configure-aws-profiles:
    name: "Configure AWS Profiles"
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - name: Configure AWS Credentials for State Account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.role-arn }}
        aws-region: ${{ inputs.region }}
    
    - name: Setup AWS Profile
      run: |
        aws configure set region ${{ env.AWS_REGION }} --profile ${{ inputs.profile }}
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile ${{ inputs.profile }}
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile ${{ inputs.profile }}
        aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile ${{ inputs.profile }}