name: Alarm for new secret scanning alerts

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  detect-secret-scanning-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ministryofjustice/github-actions/slack-github-secret-scanning-integration@slack-secret-scanning-integration
        with:
          github-token: ${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
