name: Alarm for new secret scanning alerts

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  detect-secret-scanning-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Secret Scanning Alerts
        id: secret-scammomg
        uses: advanced-security/secret-scanning-notifications@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            frequency: 24
            scope: 'repository'
            new_alerts_filepath: 'new_alerts.json'
            closed_alerts_filepath: 'closed_alerts.json'

      - run: echo ${{ steps.secret-scammomg.outputs.summary-markdown }}

    #   - name: Send notification to Slack
    #     id: slack
    #     uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 #v1.24.0
    #     with:
    #         slack-message: "New Github Secret Scanning alert:\n\n${{ steps.secret-scammomg.outputs.summary-markdown }}"
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    #       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    #   - name: Report failure to Slack
    #     if: always()
    #     uses: ravsamhq/notify-slack-action@472601e839b758e36c455b5d3e5e1a217d4807bd # 2.5.0
    #     with:
    #       status: ${{ job.status }}
    #       notify_when: "failure"
    #       notification_title: "Failed to check for low GitHub actions minutes"
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
