name: Alarm for new secret scanning alerts

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  detect-secret-scanning-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Secret Scanning Alerts
        id: secret-scammomg
        uses: advanced-security/secret-scanning-notifications@v1
        with:
            token: ${{ secrets.OPS_ENG_GENERAL_ADMIN_BOT_PAT }}
            frequency: 3000
            scope: 'repository'
            new_alerts_filepath: 'new_alerts.json'
            closed_alerts_filepath: 'closed_alerts.json'

      - name: Check number of new alerts
        id: get-new-alerts
        run: echo "new_alerts=$(jq 'length' new_alerts.json)" >> "$GITHUB_OUTPUT"

      - name: Send notification to Slack
        id: slack
        if: ${{ steps.get-new-alerts.outputs.new_alerts > 0}}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          slack-message: "Github Secret Scanning Alerts:\n\n${{ steps.secret-scammomg.outputs.summary-markdown }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    #   - name: Report failure to Slack
    #     if: always()
    #     uses: ravsamhq/notify-slack-action@472601e839b758e36c455b5d3e5e1a217d4807bd # 2.5.0
    #     with:
    #       status: ${{ job.status }}
    #       notify_when: "failure"
    #       notification_title: "Failed to check for low GitHub actions minutes"
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
