name: "♻️ Terraform Reusable Workflow"

on:
    workflow_call:
        inputs:
            path:
                required: true
                type: string
            terraform_version:
                required: true
                type: string
        secrets:
            iam_role:
                required: true
            aws_secrets_manager_role_arn:
                required: true
            repo_github_token:
                required: true
            slack_webhook_url:
                required: true
            env:
                required: false

# How to pass env vars in?
env:
  TERRAFORM_VERSION: ${{ inputs.terraform_version }}

jobs:
  terraform:
    name: "Terraform ${{ inputs.path }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:

      - name: Set environment variables
        run: |
          echo ${{ secrets.env }}

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # How to pass aws profiles in?
      - name: Configure AWS credentials for accessing AWS Secrets Manager in the DSD account
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.aws_secrets_manager_role_arn }}
            aws-region: eu-west-2

      - name: Save AWS credentials for accessing AWS Secrets Manager in the DSD account to a new profile
        run: |
            aws configure set region ${{ env.AWS_REGION }} --profile dsd_secret_manager_access_profile
            aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile dsd_secret_manager_access_profile
            aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile dsd_secret_manager_access_profile
            aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile dsd_secret_manager_access_profile

      - name: Configure AWS credentials to access state bucket in Cloud Platform account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.iam_role }}
          aws-region: eu-west-2

      - name: Post Link to Apply Pipeline
        if: github.ref == 'refs/heads/main'
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          repo-token: ${{ secrets.repo_github_token }}
          repo-token-user-login: "github-actions[bot]"
          message: |
            Your PR is applying here: https://github.com/ministryofjustice/operations-engineering/actions/workflows/cicd-terraform-github-repos.yml?query=event%3Apush+branch%3Amain

      - name: Delete old comments on PR made by bot user
        if: github.ref != 'refs/heads/main'
        uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.repo_github_token }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}
        continue-on-error: true

      - name: Terraform Format Check
        id: fmt-check
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: ls -latr; terraform init -input=false -no-color

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color

      - name: Post Plan to GitHub PR
        if: github.ref != 'refs/heads/main'
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          repo-token: ${{ secrets.repo_github_token }}
          repo-token-user-login: "github-actions[bot]"
          message: |
            ## Terraform github repositories plan
            ```
            ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
            ```

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        id: apply
        run: terraform apply -input=false -no-color -auto-approve

      - name: Report failure to Slack
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        uses: ravsamhq/notify-slack-action@472601e839b758e36c455b5d3e5e1a217d4807bd # 2.5.0
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed GitHub Action Run"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
