name: "♻️ Terraform Format"

on:
  workflow_call:

env:
  TERRAFORM_VERSION: "1.6.6"

jobs:
  terraform-fmt:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    strategy:
      matrix:
        path:
          - "repositories"
    defaults:
      run:
        working-directory: "terraform/github/${{ matrix.path }}"
    steps:
    
    - uses: actions/checkout@v4
      with:
          ref: ${{github.event.pull_request.head.ref}}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    
    - name: Terraform fmt check
      id: fmt-check
      run: terraform fmt -check -recursive -diff -no-color
      continue-on-error: true

    - name: Terraform fmt
      if: steps.fmt-check.outcome == 'failure'
      id: fmt
      run: |
        git status
        # git config --global user.name "moj-operations-engineering-bot"
        # git config --global user.email "operations-engineering@noreply.github.com"
        # terraform fmt 
        # git add *
        # git commit -m 'formatted Terraform'
        # git push 
